/**
 * Enum for standardized error codes used in the application.
 * These codes correspond to error handlers in the errorHandlers registry.
 */
export enum ErrorCode {
    // Mongoose errors
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    DUPLICATE_KEY = 'DUPLICATE_KEY',
    VALIDATION_ERROR = 'VALIDATION_ERROR',

    // JWT errors
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',

    // Bcrypt errors
    BCRYPT_ERROR = 'BCRYPT_ERROR',

    // Authentication errors
    NO_TOKEN = 'NO_TOKEN',
    SERVER_CONFIG_ERROR = 'SERVER_CONFIG_ERROR',
    INVALID_TOKEN_PAYLOAD = 'INVALID_TOKEN_PAYLOAD',
    ACCESS_DENIED = 'ACCESS_DENIED',
    AUTH_ERROR = 'AUTH_ERROR',
    NO_SECRET_JWT = 'NO_SECRET_JWT',

    // Common errors
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    INVALID_INPUT = 'INVALID_INPUT',
    INVALID_ID = 'INVALID_ID',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
    POST_NOT_FOUND = 'POST_NOT_FOUND',
    REPLY_NOT_FOUND = 'REPLY_NOT_FOUND',
    INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
    DISCUSSION_NOT_FOUND = 'DISCUSSION_NOT_FOUND',
    DISCUSSION_REPLY_NOT_FOUND = 'DISCUSSION_REPLY_NOT_FOUND',
    RSVP_NOT_FOUND = 'RSVP_NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    CAN_NOT_CREATE = 'CAN_NOT_CREATE',
    DELETE_FAILED = 'DELETE_FAILED',
    EVENT_EXCEEDED_LIMIT = 'EVENT_EXCEEDED_LIMIT',
    MAX_PARTICIPANT_EXCEEDED_LIMIT = 'MAX_PARTICIPANT_EXCEEDED_LIMIT',
    UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED',
    EVENT_CLOSED = 'EVENT_CLOSED',

    // Custom errors
    CUSTOM_ERROR = 'CUSTOM_ERROR',
}
