export enum NOTIFY_WHEN {
    ONE_HOUR_BEFORE = 'ONE_HOUR_BEFORE',
    ONE_DAY_BEFORE = 'ONE_DAY_BEFORE',
    ONE_WEEK_BEFORE = 'ONE_WEEK_BEFORE',

    TWELVE_HOURS_BEFORE = 'TWELVE_HOURS_BEFORE',
    THREE_DAY_BEFORE = 'THREE_HOURS_BEFORE',
    NONE = 'NONE',
}
