"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controllers_1 = require("../controllers/auth.controllers");
const authRoutes = (0, express_1.Router)();
const auth = new auth_controllers_1.AuthControllers();
authRoutes.post("/sign-in", auth.signIn);
authRoutes.post("/sign-up", auth.signUp);
authRoutes.post("/sign-out", auth.signOut);
exports.default = authRoutes;
